### ISSUE TITLE
Support Zone/County only feeds

### ISSUE THREAD

**Issue by zebpalmer** [zebpalmer/WeatherAlerts#5]
Currently, WeatherAlerts only supports National and State level feeds. The NWS does offer Zone and County feeds (but not samecode based feed) For basic use, pulling the zone/county needed for a samecode would save a lot of processing and bandwidth.

**Comment by sournav** [comment]
So wait you're asking to make a parser that gives warnings based on Zone or County?

**Comment by zebpalmer** [comment]
this is ancient code. like, really old.   but, iirc the current public version of this library will pull in the national CAP feed and will give you alerts based on your requested samecode.  the intent here was to check to see if requested samecodes were contained in one state and pull that state's CAP feed. 

I keep meaning to completely rewrite this app to suck less (it was a weekend project), just haven't gotten around to it.

**Comment by sournav** [comment]
Well I'm starting to make a small web scraper for the NWS warning system, just a python script. I should have a system where you can input a zone and get weather alerts. I don't know if you'd be interested in using it.

**Comment by zebpalmer** [comment]
not really.  I wrote this 7 years ago, haven't used it in 6.
